version: 2
updates:
  # Frontend app (Next.js)
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "thanks2music"
    labels:
      - "dependencies"
      - "frontend"
    # Group patch updates together to reduce PR noise
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Backend app (WordPress)
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "thanks2music"
    labels:
      - "dependencies"
      - "backend"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"

  # AI Writer app (Next.js)
  - package-ecosystem: "npm"
    directory: "/apps/ai-writer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "thanks2music"
    labels:
      - "dependencies"
      - "ai-writer"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
