
services:
  wordpress:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-wp-${ENV}
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./premium-plugins:/var/www/html/premium-plugins

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-wp-db-${ENV}
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
