/**
 * Slug Resolver Module
 *
 * Purpose:
 *   - Provide domain-specific slug resolution functions
 *   - Abstract YAML config access with clean API
 *   - Support MVP Phase 0.1 canonicalKey generation
 *   - Implement fallback chain (YAML → Claude → ASCII)
 *
 * @module lib/config/slug-resolver
 * @see {@link /notes/archive/super-mvp-scope.md} for specification
 */

import { loadYamlConfig } from './yaml-loader';
import { generateSlugWithFallback } from './slug-generator';
import type { CostTrackerService } from '@/lib/ai/cost';
import type { TitleEntry } from './types';

// ============================================================================
// Type Guards and Helper Functions
// ============================================================================

/**
 * Type guard: TitleEntry かどうかを判定
 *
 * @param value - string または TitleEntry
 * @returns TitleEntry の場合 true
 */
function isTitleEntry(value: string | TitleEntry): value is TitleEntry {
  return typeof value === 'object' && value !== null && 'slug' in value;
}

/**
 * string | TitleEntry からスラグを抽出
 *
 * @param value - string または TitleEntry
 * @returns スラグ文字列
 */
function extractSlug(value: string | TitleEntry): string {
  return isTitleEntry(value) ? value.slug : value;
}

/**
 * Resolves a Japanese anime/manga title to its romaji slug
 *
 * @description
 * Resolution order:
 * 1. Direct match in YAML (main title)
 * 2. Alias match in YAML (variants/abbreviations)
 * 3. Fallback chain: AI API → ASCII slugify
 *
 * Used for URL construction: /collabo-cafe/{work-slug}/...
 *
 * @param {string} japaneseTitle - Japanese title (e.g., "進撃の巨人", "リゼロ")
 * @param {boolean} enableFallback - Enable fallback to AI API + ASCII (default: true)
 * @param {CostTrackerService} costTracker - Optional cost tracker for recording API usage
 * @returns {Promise<string | null>} Romaji slug or null if not found and fallback disabled
 *
 * @example
 * ```typescript
 * await resolveWorkSlug("進撃の巨人");  // → "attack-on-titan" (direct match)
 * await resolveWorkSlug("リゼロ");      // → "rezero" (alias match)
 * await resolveWorkSlug("新作アニメ");  // → "shinsaku-anime" (fallback)
 * await resolveWorkSlug("Unknown", false); // → null (fallback disabled)
 * ```
 */
export async function resolveWorkSlug(
  japaneseTitle: string,
  enableFallback = true,
  costTracker?: CostTrackerService
): Promise<string | null> {
  const config = loadYamlConfig('TITLE_ROMAJI');

  // 1. 直接マッチ（メインタイトル）
  const directMatch = config.titles[japaneseTitle];
  if (directMatch) {
    const slug = extractSlug(directMatch);
    console.log(
      `[Slug Resolver] ✅ Work slug found in YAML: "${japaneseTitle}" → "${slug}"`
    );
    return slug;
  }

  // 2. エイリアス検索（表記ゆれ・略称対応）
  for (const [title, value] of Object.entries(config.titles)) {
    if (isTitleEntry(value) && value.aliases?.includes(japaneseTitle)) {
      console.log(
        `[Slug Resolver] ✅ Work slug found via alias: "${japaneseTitle}" → "${title}" → "${value.slug}"`
      );
      return value.slug;
    }
  }

  // 3. フォールバック（AI → ASCII slugify）
  if (enableFallback) {
    console.log(
      `[Slug Resolver] ⚠️ Work slug not in YAML: "${japaneseTitle}". Trying fallback...`
    );
    try {
      const fallbackSlug = await generateSlugWithFallback(
        japaneseTitle,
        'anime/manga title',
        costTracker
      );
      return fallbackSlug;
    } catch (error) {
      console.error(
        `[Slug Resolver] ❌ Fallback failed for "${japaneseTitle}":`,
        error instanceof Error ? error.message : String(error)
      );
      return null;
    }
  }

  return null;
}

/**
 * Resolves a brand/store name to its slug
 *
 * @description
 * Looks up the brand in brand-slugs.yaml
 * If not found in YAML, uses fallback chain: Claude API → ASCII slugify
 * Used for canonicalKey: {workSlug}:{storeSlug}:{eventType}:{year}
 *
 * @param {string} brandName - Brand name (e.g., "アベイル", "しまむら")
 * @param {boolean} enableFallback - Enable fallback to Claude API + ASCII (default: true)
 * @returns {Promise<string | null>} Brand slug (e.g., "avail", "shimamura") or null if not found and fallback disabled
 *
 * @example
 * ```typescript
 * // With YAML match
 * const slug = await resolveStoreSlug("アベイル");
 * console.log(slug); // "avail" (from YAML)
 *
 * // Without YAML match, fallback to Claude
 * const slug2 = await resolveStoreSlug("新店舗");
 * console.log(slug2); // "shin-tenpo" (generated by Claude)
 *
 * // Disable fallback (YAML only)
 * const slug3 = await resolveStoreSlug("Unknown", false);
 * console.log(slug3); // null
 * ```
 */
export async function resolveStoreSlug(
  brandName: string,
  enableFallback = true,
  costTracker?: CostTrackerService
): Promise<string | null> {
  // Try YAML first
  const config = loadYamlConfig('BRAND_SLUGS');
  const yamlSlug = config.brand_slugs[brandName];

  if (yamlSlug) {
    console.log(
      `[Slug Resolver] ✅ Store slug found in YAML: "${brandName}" → "${yamlSlug}"`
    );
    return yamlSlug;
  }

  // If not found and fallback enabled, use fallback chain
  if (enableFallback) {
    console.log(
      `[Slug Resolver] ⚠️ Store slug not in YAML: "${brandName}". Trying fallback...`
    );
    try {
      const fallbackSlug = await generateSlugWithFallback(
        brandName,
        'store/brand name',
        costTracker
      );
      return fallbackSlug;
    } catch (error) {
      console.error(
        `[Slug Resolver] ❌ Fallback failed for "${brandName}":`,
        error instanceof Error ? error.message : String(error)
      );
      return null;
    }
  }

  return null;
}

/**
 * Resolves an event type name to its canonical slug
 *
 * @description
 * Looks up the event type in event-type-slugs.yaml
 * Handles synonyms (e.g., "コラボカフェ" and "カフェコラボ" both map to "collabo-cafe")
 * If not found in YAML, uses fallback chain: Claude API → ASCII slugify
 *
 * @param {string} eventTypeName - Event type name (e.g., "コラボカフェ", "ポップアップストア")
 * @param {boolean} enableFallback - Enable fallback to Claude API + ASCII (default: true)
 * @returns {Promise<string | null>} Event type slug (e.g., "collabo-cafe", "pop-up-store") or null if not found and fallback disabled
 *
 * @example
 * ```typescript
 * // With YAML match (including synonyms)
 * const slug1 = await resolveEventTypeSlug("コラボカフェ");
 * const slug2 = await resolveEventTypeSlug("カフェコラボ");
 * console.log(slug1 === slug2); // true (both return "collabo-cafe")
 *
 * // Without YAML match, fallback to Claude
 * const slug3 = await resolveEventTypeSlug("新イベント");
 * console.log(slug3); // "shin-ibento" (generated by Claude)
 *
 * // Disable fallback (YAML only)
 * const slug4 = await resolveEventTypeSlug("Unknown", false);
 * console.log(slug4); // null
 * ```
 */
export async function resolveEventTypeSlug(
  eventTypeName: string,
  enableFallback = true,
  costTracker?: CostTrackerService
): Promise<string | null> {
  // Try YAML first
  const config = loadYamlConfig('EVENT_TYPE_SLUGS');
  const yamlSlug = config.event_types[eventTypeName];

  if (yamlSlug) {
    console.log(
      `[Slug Resolver] ✅ Event type slug found in YAML: "${eventTypeName}" → "${yamlSlug}"`
    );
    return yamlSlug;
  }

  // If not found and fallback enabled, use fallback chain
  if (enableFallback) {
    console.log(
      `[Slug Resolver] ⚠️ Event type slug not in YAML: "${eventTypeName}". Trying fallback...`
    );
    try {
      const fallbackSlug = await generateSlugWithFallback(
        eventTypeName,
        'event type',
        costTracker
      );
      return fallbackSlug;
    } catch (error) {
      console.error(
        `[Slug Resolver] ❌ Fallback failed for "${eventTypeName}":`,
        error instanceof Error ? error.message : String(error)
      );
      return null;
    }
  }

  return null;
}

/**
 * Resolves a prefecture name to its slug
 *
 * @description
 * Looks up the prefecture in jp-prefecture.yaml
 * Handles variants (e.g., "東京都", "東京", "都" all map to "tokyo")
 * Note: Phase 0.1 does not use prefecture slugs, but this is prepared for Phase 1+
 *
 * @param {string} prefectureName - Prefecture name (e.g., "東京都", "大阪府")
 * @returns {string | null} Prefecture slug (e.g., "tokyo", "osaka") or null if not found
 *
 * @example
 * ```typescript
 * const slug1 = resolvePrefectureSlug("東京都");
 * const slug2 = resolvePrefectureSlug("東京");
 * const slug3 = resolvePrefectureSlug("都");
 * console.log(slug1 === slug2 && slug2 === slug3); // true (all return "tokyo")
 * ```
 */
export function resolvePrefectureSlug(prefectureName: string): string | null {
  const config = loadYamlConfig('JP_PREFECTURE');
  return config.prefectures[prefectureName] || null;
}

/**
 * Resolves an array of prefecture names to their slugs
 *
 * @description
 * Batch version of resolvePrefectureSlug for Phase 1+ areas axis support.
 * Handles multiple prefectures from multi-location events.
 * Invalid prefecture names are filtered out.
 *
 * @param {string[]} prefectureNames - Array of prefecture names (e.g., ["東京都", "大阪府"])
 * @returns {{ prefectures: string[], slugs: string[] }} Object with resolved prefectures and slugs
 *
 * @see taxonomy.yaml axes.areas
 *
 * @example
 * ```typescript
 * const result = resolvePrefectureSlugs(["東京都", "大阪府", "UnknownCity"]);
 * console.log(result);
 * // {
 * //   prefectures: ["東京都", "大阪府"],  // Only valid ones
 * //   slugs: ["tokyo", "osaka"]
 * // }
 * ```
 */
export function resolvePrefectureSlugs(prefectureNames: string[]): {
  prefectures: string[];
  slugs: string[];
} {
  const config = loadYamlConfig('JP_PREFECTURE');

  const resolvedPrefectures: string[] = [];
  const resolvedSlugs: string[] = [];

  for (const name of prefectureNames) {
    const slug = config.prefectures[name];
    if (slug) {
      // Only include if slug is found and not already in the list
      if (!resolvedSlugs.includes(slug)) {
        resolvedPrefectures.push(name);
        resolvedSlugs.push(slug);
      }
    } else {
      console.warn(
        `[Slug Resolver] ⚠️ Prefecture not found in YAML: "${name}". Skipping.`
      );
    }
  }

  console.log(
    `[Slug Resolver] 📍 Resolved ${resolvedPrefectures.length}/${prefectureNames.length} prefectures: ` +
      `[${resolvedPrefectures.join(', ')}] → [${resolvedSlugs.join(', ')}]`
  );

  return {
    prefectures: resolvedPrefectures,
    slugs: resolvedSlugs,
  };
}

/**
 * Resolves a city name to its slug
 *
 * @description
 * Looks up the city in jp-prefecture.yaml major_cities section
 * Note: Phase 0.1 does not use city slugs, prepared for future use
 *
 * @param {string} cityName - City name (e.g., "新宿", "渋谷")
 * @returns {string | null} City slug (e.g., "shinjuku", "shibuya") or null if not found
 *
 * @example
 * ```typescript
 * const slug = resolveCitySlug("新宿");
 * console.log(slug); // "shinjuku"
 * ```
 */
export function resolveCitySlug(cityName: string): string | null {
  const config = loadYamlConfig('JP_PREFECTURE');
  return config.major_cities?.[cityName] || null;
}

/**
 * Gets all available work titles
 *
 * @description
 * Returns all Japanese titles from the config
 * Useful for validation or autocomplete features
 *
 * @returns {string[]} Array of Japanese titles
 *
 * @example
 * ```typescript
 * const titles = getAllWorkTitles();
 * console.log(titles); // ["作品名", "別作品", ...]
 * ```
 */
export function getAllWorkTitles(): string[] {
  const config = loadYamlConfig('TITLE_ROMAJI');
  return Object.keys(config.titles);
}

/**
 * Gets all available brand names
 *
 * @description
 * Returns all brand names from the config
 *
 * @returns {string[]} Array of brand names
 *
 * @example
 * ```typescript
 * const brands = getAllBrandNames();
 * console.log(brands); // ["アベイル", "しまむら", ...]
 * ```
 */
export function getAllBrandNames(): string[] {
  const config = loadYamlConfig('BRAND_SLUGS');
  return Object.keys(config.brand_slugs);
}

/**
 * Gets all available event type names
 *
 * @description
 * Returns all event type names (including synonyms) from the config
 *
 * @returns {string[]} Array of event type names
 *
 * @example
 * ```typescript
 * const types = getAllEventTypeNames();
 * console.log(types); // ["コラボカフェ", "カフェコラボ", "ポップアップストア", ...]
 * ```
 */
export function getAllEventTypeNames(): string[] {
  const config = loadYamlConfig('EVENT_TYPE_SLUGS');
  return Object.keys(config.event_types);
}

/**
 * Gets all available prefecture names
 *
 * @description
 * Returns all prefecture names (including variants) from the config
 *
 * @returns {string[]} Array of prefecture names
 *
 * @example
 * ```typescript
 * const prefectures = getAllPrefectureNames();
 * console.log(prefectures); // ["東京都", "東京", "都", "大阪府", ...]
 * ```
 */
export function getAllPrefectureNames(): string[] {
  const config = loadYamlConfig('JP_PREFECTURE');
  return Object.keys(config.prefectures);
}

/**
 * Validates if a work title exists in the config
 *
 * @description
 * Synchronous YAML-only existence check (direct match + alias lookup).
 * Does NOT trigger AI/ASCII fallback chain — for loose existence check only.
 *
 * @param {string} japaneseTitle - Japanese title to validate
 * @returns {boolean} True if title exists in YAML (direct or alias)
 *
 * @example
 * ```typescript
 * console.log(isValidWorkTitle("作品名")); // true
 * console.log(isValidWorkTitle("Unknown")); // false
 * ```
 */
export function isValidWorkTitle(japaneseTitle: string): boolean {
  if (!japaneseTitle) return false;
  const config = loadYamlConfig('TITLE_ROMAJI');
  // `in` checks key existence; truthy lookup would misfire on empty-string slug entries
  if (japaneseTitle in config.titles) return true;
  for (const value of Object.values(config.titles)) {
    if (isTitleEntry(value) && value.aliases?.includes(japaneseTitle)) return true;
  }
  return false;
}

/**
 * Validates if a brand name exists in the config
 *
 * @description
 * Synchronous YAML-only existence check.
 * Does NOT trigger AI/ASCII fallback chain.
 *
 * @param {string} brandName - Brand name to validate
 * @returns {boolean} True if brand exists in YAML
 *
 * @example
 * ```typescript
 * console.log(isValidBrandName("アベイル")); // true
 * console.log(isValidBrandName("Unknown")); // false
 * ```
 */
export function isValidBrandName(brandName: string): boolean {
  if (!brandName) return false;
  const config = loadYamlConfig('BRAND_SLUGS');
  return brandName in config.brand_slugs;
}

/**
 * Validates if an event type name exists in the config
 *
 * @description
 * Synchronous YAML-only existence check. Synonyms are stored as flat
 * key-value entries in event-type-slugs.yaml (e.g., 'カフェコラボ' → 'collabo-cafe'),
 * so a direct lookup covers both canonical names and synonyms.
 * Does NOT trigger AI/ASCII fallback chain.
 *
 * @param {string} eventTypeName - Event type name to validate
 * @returns {boolean} True if event type exists in YAML (canonical or synonym)
 *
 * @example
 * ```typescript
 * console.log(isValidEventTypeName("コラボカフェ"));   // true (canonical)
 * console.log(isValidEventTypeName("カフェコラボ"));   // true (synonym, flat mapping)
 * console.log(isValidEventTypeName("Unknown"));        // false
 * ```
 */
export function isValidEventTypeName(eventTypeName: string): boolean {
  if (!eventTypeName) return false;
  const config = loadYamlConfig('EVENT_TYPE_SLUGS');
  return eventTypeName in config.event_types;
}

// ============================================================================
// Title Metadata Functions (i18n/Phase2 向け)
// ============================================================================

/**
 * Get official English title for a Japanese title
 *
 * @description
 * Looks up english_title field in TitleEntry.
 * Supports both direct title match and alias lookup.
 * Useful for i18n support in Phase2.
 *
 * @param {string} japaneseTitle - Japanese title or alias
 * @returns {string | null} English title or null if not found
 *
 * @example
 * ```typescript
 * getEnglishTitle("進撃の巨人");      // → "Attack on Titan"
 * getEnglishTitle("リゼロ");          // → "Re:Zero - Starting Life in Another World"
 * getEnglishTitle("真・侍伝 YAIBA"); // → null (simple entry, no english_title)
 * ```
 */
export function getEnglishTitle(japaneseTitle: string): string | null {
  const config = loadYamlConfig('TITLE_ROMAJI');

  // 直接マッチ
  const directMatch = config.titles[japaneseTitle];
  if (directMatch && isTitleEntry(directMatch)) {
    return directMatch.english_title || null;
  }

  // エイリアスからも検索
  for (const [, value] of Object.entries(config.titles)) {
    if (isTitleEntry(value) && value.aliases?.includes(japaneseTitle)) {
      return value.english_title || null;
    }
  }

  return null;
}

/**
 * Get short title for SEO-friendly title generation
 *
 * @description
 * Looks up short_title field in TitleEntry.
 * Used when original title is 10+ characters to keep SEO titles concise.
 * Supports both direct title match and alias lookup.
 *
 * @param {string} japaneseTitle - Japanese title or alias
 * @returns {string | null} Short title or null if not defined
 *
 * @since v2.4.0
 * @see 3-title.yaml title_shortening_rules
 *
 * @example
 * ```typescript
 * getShortTitle("あの日見た花の名前を僕達はまだ知らない。"); // → "あの花"
 * getShortTitle("この素晴らしい世界に祝福を!");              // → "このすば"
 * getShortTitle("Re:ゼロから始める異世界生活");              // → "リゼロ"
 * getShortTitle("呪術廻戦");                                  // → null (< 10 chars)
 * ```
 */
export function getShortTitle(japaneseTitle: string): string | null {
  const config = loadYamlConfig('TITLE_ROMAJI');

  // 直接マッチ
  const directMatch = config.titles[japaneseTitle];
  if (directMatch && isTitleEntry(directMatch)) {
    if (directMatch.short_title) {
      console.log(
        `[Slug Resolver] 📝 Short title found: "${japaneseTitle}" → "${directMatch.short_title}"`
      );
      return directMatch.short_title;
    }
  }

  // エイリアスからも検索
  for (const [title, value] of Object.entries(config.titles)) {
    if (isTitleEntry(value) && value.aliases?.includes(japaneseTitle)) {
      if (value.short_title) {
        console.log(
          `[Slug Resolver] 📝 Short title found via alias: "${japaneseTitle}" → "${title}" → "${value.short_title}"`
        );
        return value.short_title;
      }
    }
  }

  return null;
}

/**
 * Get short title if original is 10+ characters, otherwise return original
 *
 * @description
 * Convenience function for title generation that applies the 10-character rule.
 * Returns short_title only if:
 * 1. Original title is 10+ characters
 * 2. short_title is defined in YAML
 * Otherwise returns the original title.
 *
 * @param {string} japaneseTitle - Japanese title
 * @returns {string} Short title or original title
 *
 * @since v2.4.0
 * @see 3-title.yaml title_shortening_rules
 *
 * @example
 * ```typescript
 * getDisplayTitle("あの日見た花の名前を僕達はまだ知らない。"); // → "あの花" (18 chars → short)
 * getDisplayTitle("呪術廻戦");                                  // → "呪術廻戦" (4 chars → as-is)
 * getDisplayTitle("機動戦士ガンダム 水星の魔女");              // → "水星の魔女" (13 chars, has short)
 * getDisplayTitle("進撃の巨人");                                // → "進撃の巨人" (5 chars, no short needed)
 * ```
 */
export function getDisplayTitle(japaneseTitle: string): string {
  // 10文字未満の場合はそのまま返す
  if (japaneseTitle.length < 10) {
    return japaneseTitle;
  }

  // 10文字以上の場合、short_title があれば使用
  const shortTitle = getShortTitle(japaneseTitle);
  if (shortTitle) {
    console.log(
      `[Slug Resolver] 📝 Using short title for "${japaneseTitle}" (${japaneseTitle.length} chars) → "${shortTitle}"`
    );
    return shortTitle;
  }

  return japaneseTitle;
}

/**
 * Find canonical (main) title from alias or direct match
 *
 * @description
 * Given an alias or main title, returns the canonical Japanese title.
 * Useful for normalization and deduplication.
 *
 * @param {string} aliasOrTitle - Alias or main title to look up
 * @returns {string | null} Canonical Japanese title or null if not found
 *
 * @example
 * ```typescript
 * findCanonicalTitle("リゼロ");           // → "Re:ゼロから始める異世界生活"
 * findCanonicalTitle("進撃の巨人");       // → "進撃の巨人" (already canonical)
 * findCanonicalTitle("存在しない作品");   // → null
 * ```
 */
export function findCanonicalTitle(aliasOrTitle: string): string | null {
  const config = loadYamlConfig('TITLE_ROMAJI');

  // 直接マッチ（既に正規タイトル）
  if (config.titles[aliasOrTitle]) {
    return aliasOrTitle;
  }

  // エイリアス検索
  for (const [title, value] of Object.entries(config.titles)) {
    if (isTitleEntry(value) && value.aliases?.includes(aliasOrTitle)) {
      return title;
    }
  }

  return null;
}
