/**
 * MDX Types Module
 *
 * Purpose:
 *   - Define TypeScript interfaces for MDX frontmatter
 *   - Ensure type safety for article generation
 *   - Support MVP Phase 0.1 article structure
 *
 * @module lib/mdx/types
 * @see {@link /notes/02-backlog/super-mvp-scope.md} for specification
 */

/**
 * MDX Frontmatter for Phase 0.1
 *
 * @description
 * Metadata structure for MDX article files
 * Used in Next.js for static site generation
 *
 * File path structure:
 *   content/collabo-cafe/{work-slug}/{post-id}.mdx
 *
 * Example file:
 *   content/collabo-cafe/sample-work/01jcxy4567.mdx
 *
 * @example
 * ```yaml
 * ---
 * post_id: "01jcxy4567"
 * year: 2025
 * event_type: "collabo-cafe"
 * event_title: "コラボカフェ"
 * work_title: "作品名"
 * work_titles: ["作品名", "サンリオキャラクターズ"]
 * work_slug: "work-slug"
 * slug: "01jcxy4567"
 * title: "作品名×店舗名2025が東京・大阪・福岡で開催決定"
 * date: "2025-11-19"
 * categories: ['作品名', 'カテゴリ名']
 * excerpt: "作品名と店舗名のコラボイベントが2025年12月25日から..."
 * author: "thanks2music"
 * ogImage: "/images/og-image-compressed.png"
 * ---
 * ```
 */
export interface MdxFrontmatter {
  /**
   * Post ID (10-character ULID)
   * @example "01jcxy4567"
   */
  post_id: string;

  /**
   * Event year (4-digit year)
   * @example 2025
   */
  year: number;

  /**
   * Event type slug
   * @example "collabo-cafe", "pop-up-store"
   */
  event_type: string;

  /**
   * Event type display name (Japanese)
   * @example "コラボカフェ"
   */
  event_title: string;

  /**
   * Work title (Japanese) - Primary work for URL generation
   * @example "作品名"
   */
  work_title: string;

  /**
   * Work titles (Japanese) - All works in collaboration
   * For multi-work collaborations, includes all participating works
   * @example ["キングオブプリズムSSS", "サンリオキャラクターズ"]
   */
  work_titles?: string[];

  /**
   * Work slug (romanized)
   * @example "work-slug"
   */
  work_slug: string;

  /**
   * Article slug (same as post_id)
   * @example "01jcxy4567"
   */
  slug: string;

  /**
   * Article title (SEO-optimized)
   * @example "作品名×店舗名2025が東京・大阪・福岡で開催決定"
   */
  title: string;

  /**
   * Publication date (ISO 8601 format)
   * @example "2025-11-19"
   */
  date: string;

  /**
   * Categories for taxonomy
   * @example ['作品名', 'カテゴリ名']
   */
  categories: string[];

  /**
   * Article excerpt/summary for SEO and previews
   * @example "作品名と店舗名のコラボイベントが..."
   */
  excerpt: string;

  /**
   * Author name
   * @example "thanks2music"
   */
  author: string;

  /**
   * OG Image path for social sharing
   * Phase 0.1: Default image only
   * Phase 0.2: Extracted from official site
   * @example "/images/og-image-compressed.png"
   */
  ogImage: string;

  /**
   * Optional: Venue locations (Phase 1+)
   * @example ['東京', '大阪', '福岡']
   */
  venues?: string[];

  /**
   * Optional: Venue slugs (Phase 1+)
   * @example ['tokyo', 'osaka', 'fukuoka']
   */
  venue_slugs?: string[];

  /**
   * Optional: Prefecture names (Phase 1+ - URL設計v1.1 areas軸対応)
   * @see taxonomy.yaml axes.areas
   * @example ['東京都', '大阪府']
   */
  prefectures?: string[];

  /**
   * Optional: Prefecture slugs (Phase 1+ - URL設計v1.1 areas軸対応)
   * @see jp-prefecture.yaml
   * @example ['tokyo', 'osaka']
   */
  prefecture_slugs?: string[];

  /**
   * Optional: SEO tags (将来拡張用)
   * カテゴリとは別に、検索・フィルタリング用の補助キーワード
   * @see taxonomy.yaml tag_rules
   * @example ['アニメ', '店舗名', '作者名']
   */
  tags?: string[];
}

/**
 * Input parameters for generating MDX frontmatter
 */
export interface GenerateMdxFrontmatterInput {
  /**
   * Post ID (generated or provided)
   */
  postId: string;

  /**
   * Event year
   */
  year: number;

  /**
   * Event type slug
   */
  eventType: string;

  /**
   * Event type display name
   */
  eventTitle: string;

  /**
   * Work title (Japanese) - Primary work for URL generation
   */
  workTitle: string;

  /**
   * Work titles (Japanese) - All works in collaboration
   * For multi-work collaborations, includes all participating works
   * @example ["キングオブプリズムSSS", "サンリオキャラクターズ"]
   */
  workTitles?: string[];

  /**
   * Work slug (romanized)
   */
  workSlug: string;

  /**
   * Article title (generated by Claude API or provided)
   */
  title: string;

  /**
   * Article excerpt (generated by Claude API or provided)
   */
  excerpt: string;

  /**
   * Categories (generated by Claude API or provided)
   */
  categories: string[];

  /**
   * Optional: Publication date (defaults to today)
   */
  date?: string;

  /**
   * Optional: Author name (defaults to "thanks2music")
   */
  author?: string;

  /**
   * Optional: OG Image path (defaults to default image)
   */
  ogImage?: string;

  /**
   * Optional: Prefecture names (Phase 1+ - URL設計v1.1 areas軸対応)
   * @example ['東京都', '大阪府']
   */
  prefectures?: string[];

  /**
   * Optional: Prefecture slugs (Phase 1+ - URL設計v1.1 areas軸対応)
   * @example ['tokyo', 'osaka']
   */
  prefectureSlugs?: string[];

  /**
   * Optional: SEO tags (将来拡張用)
   * @example ['アニメ', '店舗名']
   */
  tags?: string[];
}

/**
 * MDX Article structure
 */
export interface MdxArticle {
  /**
   * Frontmatter metadata
   */
  frontmatter: MdxFrontmatter;

  /**
   * Article content (Markdown body)
   */
  content: string;

  /**
   * File path for MDX file
   * Format: content/{event-type}/{work-slug}/{post-id}.mdx
   * @example "content/collabo-cafe/sample-work/01jcxy4567.mdx"
   */
  filePath: string;
}

/**
 * Default values for MDX generation
 */
export const MDX_DEFAULTS = {
  AUTHOR: 'thanks2music',
  OG_IMAGE: '/images/og-image-compressed.png',
  CONTENT_BASE_DIR: 'apps/ai-writer/content',
} as const;
