/**
 * MDX Types Module
 *
 * Purpose:
 *   - Re-export MdxFrontmatter from @revolution/schemas (Schema-SDD truth source)
 *   - Define app-local types for MDX article generation (input camelCase / file path / defaults)
 *
 * @module lib/mdx/types
 * @see shared/schemas/mdx-frontmatter.ts for the canonical MdxFrontmatter definition
 */

// Re-export MdxFrontmatter type from shared/schemas (Schema-SDD Phase 2)
export type { MdxFrontmatter } from '@revolution/schemas/mdx-frontmatter';
import type { MdxFrontmatter } from '@revolution/schemas/mdx-frontmatter';
import type { AiProviderType } from '../ai/providers/ai-provider.interface';

/**
 * Input parameters for generating MDX frontmatter
 */
export interface GenerateMdxFrontmatterInput {
  /**
   * Post ID (generated or provided)
   */
  postId: string;

  /**
   * Event year
   */
  year: number;

  /**
   * Event type slug
   */
  eventType: string;

  /**
   * Event type display name
   */
  eventTitle: string;

  /**
   * Work title (Japanese) - Primary work for URL generation
   */
  workTitle: string;

  /**
   * Work titles (Japanese) - All works in collaboration
   * For multi-work collaborations, includes all participating works
   * @example ["キングオブプリズムSSS", "サンリオキャラクターズ"]
   */
  workTitles?: string[];

  /**
   * Work slug (romanized)
   */
  workSlug: string;

  /**
   * Article title (generated by Claude API or provided)
   */
  title: string;

  /**
   * Article excerpt (generated by Claude API or provided)
   */
  excerpt: string;

  /**
   * Categories (generated by Claude API or provided)
   */
  categories: string[];

  /**
   * Optional: Publication date (defaults to today)
   */
  date?: string;

  /**
   * Optional: Author name (defaults to "thanks2music")
   */
  author?: string;

  /**
   * Optional: OG Image path (defaults to default image)
   */
  ogImage?: string;

  /**
   * Optional: Prefecture names (Phase 1+ - URL設計v1.1 areas軸対応)
   * @example ['東京都', '大阪府']
   */
  prefectures?: string[];

  /**
   * Optional: Prefecture slugs (Phase 1+ - URL設計v1.1 areas軸対応)
   * @example ['tokyo', 'osaka']
   */
  prefectureSlugs?: string[];

  /**
   * Optional: SEO tags (将来拡張用)
   * @example ['アニメ', '店舗名']
   */
  tags?: string[];

  /**
   * Optional: AI provider used for article generation (Debug metadata)
   * Records which LLM provider was used to generate this article
   * @example "gemini", "anthropic", "openai"
   */
  aiProvider?: AiProviderType;

  /**
   * Optional: AI model name used for article generation (Debug metadata)
   * Records the specific model version used for generation
   * @example "gemini-2.0-flash-exp", "claude-3-5-sonnet-20241022", "gpt-4o-mini"
   */
  aiModel?: string;
}

/**
 * MDX Article structure
 */
export interface MdxArticle {
  /**
   * Frontmatter metadata
   */
  frontmatter: MdxFrontmatter;

  /**
   * Article content (Markdown body)
   */
  content: string;

  /**
   * File path for MDX file
   * Format: content/{event-type}/{work-slug}/{post-id}.mdx
   * @example "content/collabo-cafe/sample-work/01jcxy4567.mdx"
   */
  filePath: string;
}

/**
 * Default values for MDX generation
 */
export const MDX_DEFAULTS = {
  AUTHOR: 'thanks2music',
  OG_IMAGE: '/images/og-image-compressed.png',
  CONTENT_BASE_DIR: 'apps/ai-writer/content',
} as const;
