/**
 * MDX Types Module
 *
 * Purpose:
 *   - Re-export MdxFrontmatter from @revolution/schemas (Schema-SDD truth source)
 *   - Define app-local types for MDX article generation (input camelCase / file path / defaults)
 *
 * @module lib/mdx/types
 * @see shared/schemas/mdx-frontmatter.ts for the canonical MdxFrontmatter definition
 */

// Re-export MdxFrontmatter type from shared/schemas (Schema-SDD Phase 2)
import type { MdxFrontmatter, EventData } from '@revolution/schemas/mdx-frontmatter';
import type { AiProviderType } from '../ai/providers/ai-provider.interface';

export type { MdxFrontmatter, EventData };

/**
 * Input parameters for generating MDX frontmatter
 */
export interface GenerateMdxFrontmatterInput {
  /**
   * Post ID (generated or provided)
   */
  postId: string;

  /**
   * Event year
   */
  year: number;

  /**
   * Event type slug
   */
  eventType: string;

  /**
   * Event type display name
   */
  eventTitle: string;

  /**
   * Work title (Japanese) - Primary work for URL generation
   */
  workTitle: string;

  /**
   * Work titles (Japanese) - All works in collaboration
   * For multi-work collaborations, includes all participating works
   * @example ["キングオブプリズムSSS", "サンリオキャラクターズ"]
   */
  workTitles?: string[];

  /**
   * Work slug (romanized)
   */
  workSlug: string;

  /**
   * Article title (generated by Claude API or provided)
   */
  title: string;

  /**
   * Article excerpt (generated by Claude API or provided)
   */
  excerpt: string;

  /**
   * Categories (generated by Claude API or provided)
   */
  categories: string[];

  /**
   * Optional: Publication date (defaults to today)
   */
  date?: string;

  /**
   * Optional: Author name (defaults to "thanks2music")
   */
  author?: string;

  /**
   * Optional: OG Image path (defaults to default image)
   */
  ogImage?: string;

  /**
   * Optional: Prefecture names (Phase 1+ - URL設計v1.1 areas軸対応)
   * @example ['東京都', '大阪府']
   */
  prefectures?: string[];

  /**
   * Optional: Prefecture slugs (Phase 1+ - URL設計v1.1 areas軸対応)
   * @example ['tokyo', 'osaka']
   */
  prefectureSlugs?: string[];

  /**
   * Optional: SEO tags (将来拡張用)
   * @example ['アニメ', '店舗名']
   */
  tags?: string[];

  /**
   * Optional: AI provider used for article generation (Debug metadata)
   * Records which LLM provider was used to generate this article
   * @example "gemini", "anthropic", "openai"
   */
  aiProvider?: AiProviderType;

  /**
   * Optional: AI model name used for article generation (Debug metadata)
   * Records the specific model version used for generation
   * @example "gemini-2.0-flash-exp", "claude-3-5-sonnet-20241022", "gpt-4o-mini"
   */
  aiModel?: string;

  // ---------------------------------------------------------------------------
  // Sprint C-α (MVP §11) で追加: EventFactCard 4 フィールド + event_data
  // ---------------------------------------------------------------------------
  // 命名規則: 入力側は camelCase (本 interface)、frontmatter 出力側は snake_case
  //   (MdxFrontmatterSchema、既存の workTitle → work_title と同パターン)
  // orchestrator (article-generation-mdx.service.ts、Step 5.5) が
  //   `apps/ai-writer/lib/utils/event-fact-card-mapper.ts` の
  //   `extractEventFactCardFields(...)` で導出した値を渡す
  // ---------------------------------------------------------------------------

  /**
   * Optional: 開催開始日 (YYYY-MM-DD、ISO 8601 date)
   * @description
   * MVP §11 EventFactCard 用。`z.iso.date()` 適合済の値を渡す
   * (`extractEventFactCardFields` の Layer 1 で検証済)。
   * Frontend の EventFactCard コンポーネントが「あと N 日」黄色バッジ表示に使用。
   */
  eventStartDate?: string;

  /**
   * Optional: 開催終了日 (YYYY-MM-DD、ISO 8601 date)
   * @description
   * `終了.未定 === true` の場合や無効入力時は undefined 渡し (Q4=C helper で担保)。
   */
  eventEndDate?: string;

  /**
   * Optional: 会場名 (通常 detailedExtraction.店舗名 と同一)
   */
  venue?: string;

  /**
   * Optional: 公式サイトURL (`z.string().url()` 適合済)
   */
  officialUrl?: string;

  /**
   * Optional: 開催ブロック雛形 (MVP §11、Sprint C-α で新設、BOSS 承認 α 2026-07-12)
   * @description
   * `EventDataSchema` (`@revolution/schemas/mdx-frontmatter`) 準拠。
   * AI Writer プロンプト応答の `event_data` オブジェクトを Zod parse 済で渡す。
   * `primary_category_slug` / `title_slugs[]` / `supplementary_category_slugs[]` (maxItems:2) /
   * `occurrences[]` を含む。DB upsert 本実装は Sprint D、MVP は雛形応答のみ。
   */
  eventData?: EventData;
}

/**
 * MDX Article structure
 */
export interface MdxArticle {
  /**
   * Frontmatter metadata
   */
  frontmatter: MdxFrontmatter;

  /**
   * Article content (Markdown body)
   */
  content: string;

  /**
   * File path for MDX file
   * Format: content/{event-type}/{work-slug}/{post-id}.mdx
   * @example "content/collabo-cafe/sample-work/01jcxy4567.mdx"
   */
  filePath: string;
}

/**
 * Default values for MDX generation
 */
export const MDX_DEFAULTS = {
  AUTHOR: 'thanks2music',
  OG_IMAGE: '/images/og-image-compressed.png',
  CONTENT_BASE_DIR: 'apps/ai-writer/content',
} as const;
